### ISSUE TITLE
simple mistake in mutate crashes R session

### ISSUE THREAD

**Issue by clayms** [hadley/dplyr#1709]
I know the following has an error in that it should end with something like `mutate(N = max(X1))`, but should the following code crash R completely?

```
dat <- data.frame(matrix(rnorm(1000 * 10), 1000))
group <- rbinom(1000,20,.1)
df <- cbind(group, dat)

library(dplyr)

df <- df %>% 
      group_by(group) %>% 
      mutate(N = max)
```

I was barely able to grab the following:

```
Assertion failed!

Program: C:\Program Files\RStudio\bin\x64\rsession.exe
File: d:/RCompile/CRANpkg/lib/3.2/BH/include/boost/smart_ptr/scoped_ptr.hpp, Line 105

Expression: px != 0

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.2       assertthat_0.1 parallel_3.2.3 DBI_0.3.1      tools_3.2.3   
[7] Rcpp_0.12.3   
```

**Comment by hadley** [comment]
Already fixed in dev

**Comment by santhoshn24** [comment]
Hi,
Im getting the same an error when i run below code

**"This application has requested the Runtime to terminate it in an usual way. 
Please contact the application's support team for more information"**

Tried reinstalling both dplyr and Rcpp but still the same, please help.

I have a Win 7 32 bit , R 3.3.1 and Rstudio 0.99.669
Attached diagnostics report
[diagnostics-report.txt](https://github.com/hadley/dplyr/files/410975/diagnostics-report.txt)

Code which threw error, although same mutate option worked for previous operations.
train = train %>%
 mutate (grad = as.numeric(Education == "Graduate"),
             (Ug =    as.numeric (Education == "Not Graduate"))) %>%
 select(-Education)

**Comment by hadley** [comment]
You need to install the preview release of RStudio

**Comment by santhoshn24** [comment]
Hi Hadley,

I've installed the latest version RStudio Desktop 0.99.903, but  its still throwing me the same error.
[diagnostics-report.txt](https://github.com/hadley/dplyr/files/412605/diagnostics-report.txt)

**Comment by kevinushey** [comment]
You can install the preview release of RStudio here: https://www.rstudio.com/products/rstudio/download/preview/
